---
grails:
    profile: web
    codegen:
        defaultPackage: demo
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            dbCreate: create-drop
            url: jdbc:oracle:thin:@//ocs28-scan.internal.sanger.ac.uk:1521/cost
            driverClassName: oracle.jdbc.OracleDriver
            username: "cosmic_download"
            password: "cosmic1234"
        dataSourceOracle:
            dbCreate: validate
            url: jdbc:oracle:thin:@//ocs27-scan.internal.sanger.ac.uk:1521/cosn
            driverClassName: oracle.jdbc.OracleDriver
            username: "cosmic_rest"
            password: "cosmic2017"
    test:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            dbCreate: create-drop
            url: jdbc:oracle:thin:@//ocs28-scan.internal.sanger.ac.uk:1521/cost
            driverClassName: oracle.jdbc.OracleDriver
            username: "cosmic_download"
            password: "cosmic1234"
    production:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            dbCreate: create-drop
            url: jdbc:oracle:thin:@//ocs28-scan.internal.sanger.ac.uk:1521/cost
            driverClassName: oracle.jdbc.OracleDriver
            username: "cosmic_download"
            password: "cosmic1234"
